set(_CATKIN_CURRENT_PACKAGE "legged_bot_hardware")
set(legged_bot_hardware_VERSION "0.0.0")
set(legged_bot_hardware_MAINTAINER "dohyeon <dohyeon@psotech.ac.kr>")
set(legged_bot_hardware_PACKAGE_FORMAT "2")
set(legged_bot_hardware_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "rosserial_arduino" "tf" "rosserial_client" "genmsg")
set(legged_bot_hardware_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "rosserial_arduino" "tf" "rosserial_client" "genmsg")
set(legged_bot_hardware_BUILDTOOL_DEPENDS "catkin")
set(legged_bot_hardware_BUILDTOOL_EXPORT_DEPENDS )
set(legged_bot_hardware_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "rosserial_arduino" "tf" "rosserial_client" "genmsg")
set(legged_bot_hardware_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "rosserial_arduino" "tf" "rosserial_client" "genmsg")
set(legged_bot_hardware_TEST_DEPENDS )
set(legged_bot_hardware_DOC_DEPENDS )
set(legged_bot_hardware_URL_WEBSITE "")
set(legged_bot_hardware_URL_BUGTRACKER "")
set(legged_bot_hardware_URL_REPOSITORY "")
set(legged_bot_hardware_DEPRECATED "")